# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - make install-deps
builds:
  -
    dir: src
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
    goarm:
      - "6"
      - "7"

archives:
  -
    files:
    - LICENSE
    - README.md
    - CHANGELOG.md
checksum:
  name_template: 'checksums.txt'
changelog:
  skip: true
