{
 "title": "F2B",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DataSource", "label": "Data Source", "query": "prometheus" },
   { "name": "instance", "label": "Instance", "query": { "query": "f2b_up" } }
  ]
 },
 "panels": [
  {
   "title": "F2B Config",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "f2b_config_jail_max_retries{instance=~\"$instance\"}",
     "legendFormat": "{{jail}}"
    },
    {
     "expr": "f2b_config_jail_ban_time{instance=~\"$instance\"}",
     "legendFormat": "{{jail}}"
    },
    {
     "expr": "f2b_config_jail_find_time{instance=~\"$instance\"}",
     "legendFormat": "{{jail}}"
    }
   ]
  },
  {
   "title": "Fail2Ban Failures (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "f2b_jail_failed_total{instance=~\"$instance\"}",
     "legendFormat": "{{jail}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Fail2Ban Bans (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "f2b_jail_banned_total{instance=~\"$instance\"}",
     "legendFormat": "{{jail}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Fail2Ban Failures (Current)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "f2b_jail_failed_current{instance=~\"$instance\"}",
     "legendFormat": "{{jail}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Fail2Ban Bans (Current)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "f2b_jail_banned_current{instance=~\"$instance\"}",
     "legendFormat": "{{jail}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Fail2Ban Up",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "f2b_up{instance=~\"$instance\"}",
     "legendFormat": "Up ({{instance}})"
    }
   ]
  },
  {
   "title": "Fail2Ban Exporter Errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(f2b_errors{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{type}} ({{instance}})"
    }
   ]
  }
 ]
}